Remove gh-pages
It causes too many errors..

```
SSL_connect returned=1 errno=0 state=error: certificate verify failed

Error: No repo name found. Specify using PAGES_REPO_NWO environment
variables,
```